import { Share, Platform } from 'react-native';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { MonthSummary, TenantBillDetails, MainMeterAccount } from '../types';
import { formatCurrency, formatUnits, formatMonthLabel } from './calculations';

export const generateCombinedReportText = (
  mainMeter: MainMeterAccount | undefined,
  summary: MonthSummary
): string => {
  const accountName = mainMeter ? mainMeter.name : 'Main Meter';
  const monthLabel = formatMonthLabel(summary.month);

  let text = `⚡ *ELECTRICITY BILL SPLIT REPORT*\n`;
  text += `📍 *Property/Account:* ${accountName}\n`;
  text += `📅 *Billing Cycle:* ${monthLabel}\n`;
  text += `------------------------------------\n`;
  text += `💵 *Total Main Bill Amount:* ${formatCurrency(summary.totalMainBillAmount)}\n`;
  text += `📊 *Total Sub-Meter Units:* ${formatUnits(summary.totalSubMeterUnits)}\n`;
  text += `⚡ *Calculated Rate:* ${formatCurrency(summary.costPerUnit)} / Unit\n`;
  text += `------------------------------------\n`;
  text += `📋 *TENANT BREAKDOWN:*\n\n`;

  summary.tenantBills.forEach((tb, index) => {
    text += `${index + 1}. *${tb.tenant.name}* (${tb.tenant.meterNumber})\n`;
    text += `   • Previous Reading: ${tb.previousReadingUsed}\n`;
    text += `   • Current Reading: ${tb.currentReadingUsed}\n`;
    text += `   • Consumed Units: ${formatUnits(tb.unitsConsumed)}\n`;
    text += `   • *Payable Amount:* ${formatCurrency(tb.calculatedBillAmount)}\n\n`;
  });

  text += `------------------------------------\n`;
  text += `Generated by WattSplit App ⚡`;

  return text;
};

export const generateTenantReceiptText = (
  mainMeter: MainMeterAccount | undefined,
  month: string,
  tenantBill: TenantBillDetails,
  costPerUnit: number
): string => {
  const accountName = mainMeter ? mainMeter.name : 'Main Meter';
  const monthLabel = formatMonthLabel(month);

  let text = `⚡ *ELECTRICITY SUB-METER RECEIPT*\n`;
  text += `👤 *Tenant:* ${tenantBill.tenant.name}\n`;
  text += `📟 *Sub-Meter No:* ${tenantBill.tenant.meterNumber}\n`;
  text += `📍 *Property:* ${accountName}\n`;
  text += `📅 *Billing Cycle:* ${monthLabel}\n`;
  text += `------------------------------------\n`;
  text += `• Previous Reading: ${tenantBill.previousReadingUsed}\n`;
  text += `• Current Reading: ${tenantBill.currentReadingUsed}\n`;
  text += `• Net Units Consumed: ${formatUnits(tenantBill.unitsConsumed)}\n`;
  text += `• Applicable Rate: ${formatCurrency(costPerUnit)} / Unit\n`;
  text += `------------------------------------\n`;
  text += `💰 *TOTAL AMOUNT PAYABLE: ${formatCurrency(tenantBill.calculatedBillAmount)}*\n`;
  text += `------------------------------------\n`;
  text += `Please pay on time. Thank you! 🙏\n`;
  text += `Generated by WattSplit App ⚡`;

  return text;
};

export const shareTextReport = async (title: string, message: string): Promise<void> => {
  try {
    await Share.share({
      title,
      message,
    });
  } catch (error) {
    console.error('Error sharing report:', error);
  }
};

export const generateAndShareCombinedPDF = async (
  mainMeter: MainMeterAccount | undefined,
  summary: MonthSummary
): Promise<void> => {
  const accountName = mainMeter ? mainMeter.name : 'Main Meter';
  const monthLabel = formatMonthLabel(summary.month);

  const tenantRowsHtml = summary.tenantBills
    .map(
      (tb, idx) => `
    <tr style="background-color: ${idx % 2 === 0 ? '#f8fafc' : '#ffffff'};">
      <td style="padding: 10px; border-bottom: 1px solid #e2e8f0; font-weight: 600;">${tb.tenant.name}</td>
      <td style="padding: 10px; border-bottom: 1px solid #e2e8f0;">${tb.tenant.meterNumber}</td>
      <td style="padding: 10px; border-bottom: 1px solid #e2e8f0;">${tb.previousReadingUsed}</td>
      <td style="padding: 10px; border-bottom: 1px solid #e2e8f0;">${tb.currentReadingUsed}</td>
      <td style="padding: 10px; border-bottom: 1px solid #e2e8f0; font-weight: 600; color: #4f46e5;">${tb.unitsConsumed.toFixed(1)}</td>
      <td style="padding: 10px; border-bottom: 1px solid #e2e8f0; font-weight: 700; color: #059669;">${formatCurrency(tb.calculatedBillAmount)}</td>
    </tr>
  `
    )
    .join('');

  const htmlContent = `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8" />
        <title>Electricity Bill Split Report</title>
        <style>
          body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #1e293b; padding: 30px; margin: 0; }
          .header { text-align: center; border-bottom: 2px solid #4f46e5; padding-bottom: 16px; margin-bottom: 24px; }
          .header h1 { color: #4f46e5; margin: 0; font-size: 24px; }
          .header p { color: #64748b; margin: 4px 0 0 0; font-size: 14px; }
          .summary-card { background-color: #f1f5f9; border-radius: 12px; padding: 18px; margin-bottom: 24px; display: flex; justify-content: space-between; }
          .stat-box { flex: 1; text-align: center; border-right: 1px solid #cbd5e1; }
          .stat-box:last-child { border-right: none; }
          .stat-label { font-size: 11px; text-transform: uppercase; color: #64748b; font-weight: 700; }
          .stat-value { font-size: 18px; font-weight: 800; color: #0f172a; margin-top: 4px; }
          table { width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 13px; }
          th { background-color: #4f46e5; color: white; text-align: left; padding: 12px 10px; font-size: 12px; text-transform: uppercase; }
          .footer { margin-top: 40px; text-align: center; font-size: 12px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 16px; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>⚡ ${accountName} - Bill Split Report</h1>
          <p>Billing Cycle: ${monthLabel} | Generated on ${new Date().toLocaleDateString()}</p>
        </div>

        <div class="summary-card">
          <div class="stat-box">
            <div class="stat-label">Total Main Bill</div>
            <div class="stat-value" style="color: #4f46e5;">${formatCurrency(summary.totalMainBillAmount)}</div>
          </div>
          <div class="stat-box">
            <div class="stat-label">Total Sub Units</div>
            <div class="stat-value">${summary.totalSubMeterUnits.toFixed(1)} U</div>
          </div>
          <div class="stat-box">
            <div class="stat-label">Calculated Rate</div>
            <div class="stat-value" style="color: #059669;">${formatCurrency(summary.costPerUnit)}/U</div>
          </div>
        </div>

        <h3 style="margin-bottom: 8px; color: #0f172a;">Tenant Sub-Meters Breakdown</h3>
        <table>
          <thead>
            <tr>
              <th>Tenant Name</th>
              <th>Meter No</th>
              <th>Prev Reading</th>
              <th>Curr Reading</th>
              <th>Units</th>
              <th>Payable (₹)</th>
            </tr>
          </thead>
          <tbody>
            ${tenantRowsHtml}
          </tbody>
        </table>

        <div class="footer">
          WattSplit Smart Electricity Bill Splitter App ⚡
        </div>
      </body>
    </html>
  `;

  try {
    const { uri } = await Print.printToFileAsync({ html: htmlContent });
    if (await Sharing.isAvailableAsync()) {
      await Sharing.shareAsync(uri, {
        UTI: '.pdf',
        mimeType: 'application/pdf',
        dialogTitle: `${accountName} Bill Report ${monthLabel}`,
      });
    } else {
      await Share.share({ title: 'Bill Report', url: uri });
    }
  } catch (error) {
    console.error('Error generating PDF:', error);
  }
};
